name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze, and Deploy
    runs-on: self-hosted

    steps:

      # 1Ô∏è‚É£ Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2Ô∏è‚É£ Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # 3Ô∏è‚É£ Setup Maven
      - name: Setup Maven
        shell: powershell
        run: |
          $mavenDir = "$env:USERPROFILE\maven\apache-maven-3.8.8"
          if (-Not (Test-Path "$mavenDir\bin\mvn.cmd")) {
              Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip" -OutFile "maven.zip"
              Expand-Archive -Path "maven.zip" -DestinationPath "$env:USERPROFILE\maven"
          }
          echo "MAVEN_HOME=$mavenDir" >> $env:GITHUB_ENV
          echo "$mavenDir\bin" >> $env:GITHUB_PATH

      # 4Ô∏è‚É£ Build et SonarQube analysis
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        shell: powershell
        run: |
          mvn -B verify sonar:sonar `
            -Dsonar.projectKey="user-management" `
            -Dsonar.sources="." `
            -Dsonar.host.url="$env:SONAR_HOST_URL" `
            -Dsonar.login="$env:SONAR_TOKEN"

      # 5Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        shell: powershell
        run: docker build -t carikk/quality-gate:latest .

      # 6Ô∏è‚É£ Login Docker
      - name: Log in to DockerHub
        shell: powershell
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      # 7Ô∏è‚É£ Push Docker image
      - name: Push Docker image
        shell: powershell
        run: docker push carikk/quality-gate:latest

      # 8Ô∏è‚É£ Setup kubeconfig
      - name: Set up kubeconfig
        shell: powershell
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          kubectl config use-context docker-desktop
          kubectl config set-context --current --namespace=ensakh

      # 9Ô∏è‚É£ Verify Kubernetes context
      - name: Verify Kubernetes context
        shell: powershell
        run: |
          kubectl config current-context
          kubectl get namespaces

      # üîü Deploy to Kubernetes
      - name: Deploy to kube
        shell: powershell
        run: kubectl apply -f k8s/deployment.yaml

      # 11Ô∏è‚É£ Verify deployment
      - name: Verify Kubernetes deployment
        shell: powershell
        run: |
          kubectl get nodes
          kubectl get namespaces
          kubectl get pods
